# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 4
batch_size: 2
lr: 0.0004

train_data: !new:speechbrain.data_io.legacy.ExtendedCSVDataset
    csvpath: !ref <csv_train>
    output_keys: [wav, spk_id]
    sorting: ascending
    replacements:
        data_folder: !ref <data_folder>

valid_data: !new:speechbrain.data_io.legacy.ExtendedCSVDataset
    csvpath: !ref <csv_train>
    output_keys: [wav, spk_id]
    sorting: ascending
    replacements:
        data_folder: !ref <data_folder>

test_data: !new:speechbrain.data_io.legacy.ExtendedCSVDataset
    csvpath: !ref <csv_test>
    output_keys: [wav, spk_id]
    sorting: ascending
    replacements:
        data_folder: !ref <data_folder>

label_encoder: !new:speechbrain.data_io.encoder.CategoricalEncoder

loader_kwargs:
    batch_size: !ref <batch_size>
    collate_fn: !name:speechbrain.data_io.batch.PaddedBatch
        padded_keys: ["wav"]

compute_features: !new:speechbrain.lobes.features.MFCC
mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

linear1: !new:speechbrain.nnet.linear.Linear
    input_size: 660
    n_neurons: 1024
    bias: False

activation: !new:torch.nn.LeakyReLU

linear2: !new:speechbrain.nnet.linear.Linear
    input_size: 1024
    n_neurons: 2
    bias: False

modules:
    linear1: !ref <linear1>
    linear2: !ref <linear2>
    mean_var_norm: !ref <mean_var_norm>

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

compute_cost: !name:speechbrain.nnet.losses.nll_loss

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch
