# Basic parameters
sample_rate: 16000

# Data files
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Neural Parameters
N_epochs: 40
N_batch: 1
lr: 0.06
blank_id: 42
size_output: 43
device: cuda

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav, spk_id]
    replacements:
        $data_folder: !ref <data_folder>

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <N_batch>
    csv_read: [wav, spk_id]
    replacements:
        $data_folder: !ref <data_folder>

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    csv_read: [wav, spk_id]
    replacements:
        $data_folder: !ref <data_folder>

compute_features: !new:speechbrain.lobes.features.mfcc.MFCC

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

encoder_rnn: !new:speechbrain.nnet.RNN.RNN
    rnn_type: gru
    n_neurons: 256
    nonlinearity: tanh
    num_layers: 2
    dropout: 0.15
    bidirectional: True

encoder_lin: !new:speechbrain.nnet.linear.Linear
    n_neurons: 43  # 42 phonemes + 1 blank
    bias: False

embedding_PN: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <size_output>
    consider_as_one_hot: True # consider blank as zero vect
    blank_id: !ref <blank_id>

decoder_rnn: !new:speechbrain.nnet.RNN.RNN
    rnn_type: gru
    n_neurons: 128
    nonlinearity: tanh
    num_layers: 1
    dropout: 0.15
    bidirectional: False
    return_hidden: True

decoder_lin: !new:speechbrain.nnet.linear.Linear
    n_neurons: 43  # 42 phonemes + 1 blank
    bias: True

joint_lin: !new:speechbrain.nnet.linear.Linear
    n_neurons: 43  # 42 phonemes + 1 blank
    bias: True

Tjoint: !new:speechbrain.nnet.transducer.transducer_joint.Transducer_joint
    joint_network: !ref <joint_lin>
    joint: sum # joint: [sum|concat]
    nonlinearity: tanh

output: !new:speechbrain.nnet.linear.Linear
    n_neurons: 43  # 42 phonemes + 1 blank
    bias: False

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !new:speechbrain.nnet.losses.ComputeCost
    cost_type: transducer
    blank_index: !ref <blank_id>

optimizer: !new:speechbrain.nnet.optimizers.Optimize
    optimizer_type: adam
    learning_rate: !ref <lr>
