# default sets up the environment for all jobs:
default:
  # Aku's custom SpeechBrain CI environment, based on the
  # official Python image
  image: gastron/speechbrain-ci:latest

all-tests:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID  # Execute only in merge request context
  script:
    - python -V  # Print out python version for debugging
    # Lint-tests:
    - pip install -r lint-requirements.txt
    - black --check speechbrain
    - flake8 speechbrain
    - black --check tests 
    - flake8 tests 
    - black --check recipes
    - flake8 recipes
    # Unit-tests:
    - pip install -r requirements.txt
    - pip install --editable .
    - pytest tests
    - pytest --doctest-modules speechbrain
