repos:
  - repo: local 
    hooks:
    - id: unittests
      name: unittests
      entry: pytest tests
      language: python
      pass_filenames: false
      always_run: true
      require_serial: false

  - repo: local 
    hooks:
    - id: doctests 
      name: doctests
      entry: pytest --doctest-modules speechbrain
      language: python
      pass_filenames: false
      always_run: true
      require_serial: false
