# Basic parameters
output_folder: exp/minimal/nmf_sourcesep
sample_rate: 16000

# Data files
data_folder: ../../../../samples/audio_samples/sourcesep_samples/minimal_data
csv_train: !ref <data_folder>/csv_example_sourcesep.csv
#csv_valid: !ref <data_folder>/csv_example_sourcesep.csv
#csv_test: !ref <data_folder>/csv_example_sourcesep.csv

# NMF parameters
N_epochs: 200
K: 100 
N_batch: 100

train_loader: !speechbrain.data_io.data_io.DataLoaderFactory &loader
    csv_file: !ref <csv_train>
    batch_size: !ref <N_batch>
    csv_read: [wav]
    output_folder: !ref <output_folder>
    replacements:
     $data_folder: !ref <data_folder>

#valid_loader: !speechbrain.data_io.data_io.DataLoaderFactory
#    <<: *loader
#    csv_file: !ref <csv_valid>

        #test_loader: !speechbrain.data_io.data_io.DataLoaderFactory
        #<<: *loader
        #csv_file: !ref <csv_test>
        #batch_size: 1

compute_features: !speechbrain.lobes.features.fbank.Fbank
    feature_type: spectrogram

#mean_var_norm: !speechbrain.processing.features.mean_var_norm
    #norm_type: global

    #linear1: !speechbrain.nnet.linear.Linear
    #n_neurons: 1024
    #bias: False

    #activation: !torch.nn.LeakyReLU

    #linear2: !speechbrain.nnet.linear.Linear
    #n_neurons: 43
    #bias: False

    #softmax: !speechbrain.nnet.activations.Softmax
    #apply_log: True

    #compute_cost: !speechbrain.nnet.losses.ComputeCost
    #cost_type: [nll]

    #compute_error: !speechbrain.nnet.losses.ComputeCost
    #cost_type: [error]

    #optimizer: !speechbrain.nnet.optimizers.Optimize
    #optimizer_type: adam
    #learning_rate: !ref <lr>
