# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
use_tensorboard: True
tensorboard_logs: runs/4-checkpointing
output_folder: !ref results/conv_tasnet/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Neural Parameters
N_epochs: 100
N_batch: 1
lr: 0.0002
train_onthefly: False
loss_fn: 'sisnr'
progressbar: True

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref wsj_tr.csv
    batch_size: !ref <N_batch>
    sentence_sorting: random
    csv_read: [mix_wav, s1_wav, s2_wav]

val_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref wsj_cv.csv
    batch_size: !ref <N_batch>
    sentence_sorting: random
    csv_read: [mix_wav, s1_wav, s2_wav]

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref wsj_tt.csv
    batch_size: !ref <N_batch>
    sentence_sorting: random
    csv_read: [mix_wav, s1_wav, s2_wav]


conv_tasnet: !new:speechbrain.nnet.conv_tasnet.ConvTasNet
    N: 256
    L: 20
    B: 256
    H: 512
    P: 3
    X: 8
    R: 4
    C: 2
    norm_type: 'gLN'
    causal: False
    mask_nonlinear: 'relu'

optimizer: !new:speechbrain.nnet.optimizers.Adam_Optimizer
    learning_rate: !ref <lr>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <conv_tasnet>
        optimizer: !ref <optimizer>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
    summary_fns:
        PER: !name:speechbrain.utils.train_logger.summarize_error_rate
