# Seed needs to be set at top of yaml, before objects with parameters are made
# NOTE: Seed does not guarantee replicability with CTC
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER

# Neural Parameters
N_epochs: 30
N_batch: 1
lr: 0.002

# Model parameters
activation: !new:torch.nn.LeakyReLU

label_encoder: !new:speechbrain.data_io.encoder.CTCTextEncoder
blank_index: 0

common_dynamic_items:
    phn_list:
        func: !name:speechbrain.utils.data_utils.split_by_whitespace
        argkeys: [phn]
    phn_encoded:
        func: !ref <label_encoder.encode_sequence_torch>
        argkeys: [phn_list]
    sig:
        func: !name:speechbrain.data_io.data_io.read_audio
        argkeys: [wav]
common_output_keys: ["id", "sig", "phn_encoded"]

train_data: !apply:speechbrain.data_io.dataset.DynamicItemDataset.from_json
    json_path: !ref <data_folder>/train.json
    replacements:
        data_root: !ref <data_folder>
    dynamic_items: !ref <common_dynamic_items>
    output_keys: !ref <common_output_keys>

valid_data: !apply:speechbrain.data_io.dataset.DynamicItemDataset.from_json
    json_path: !ref <data_folder>/dev.json
    replacements:
        data_root: !ref <data_folder>
    dynamic_items: !ref <common_dynamic_items>
    output_keys: !ref <common_output_keys>

compute_features: !new:speechbrain.lobes.features.MFCC

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

model: !new:speechbrain.nnet.containers.Sequential
    input_shape: [!ref <N_batch>, null, 660]  # input_size
    conv1: !name:speechbrain.nnet.complex_networks.CNN.ComplexConv1d
        out_channels: 16
        kernel_size: 3
    nrm1: !name:speechbrain.nnet.complex_networks.normalization.ComplexLayerNorm
    act1: !ref <activation>
    conv2: !name:speechbrain.nnet.complex_networks.CNN.ComplexConv1d
        out_channels: 32
        kernel_size: 3
    nrm2: !name:speechbrain.nnet.complex_networks.normalization.ComplexLayerNorm
    act2: !ref <activation>
    pooling: !new:speechbrain.nnet.pooling.Pooling1d
        pool_type: "avg"
        kernel_size: 3
    RNN: !name:speechbrain.nnet.complex_networks.RNN.ComplexLiGRU
        hidden_size: 64
        bidirectional: True
    linear: !name:speechbrain.nnet.linear.Linear
        n_neurons: 43  # 42 phonemes + 1 blank
        bias: False
    softmax: !new:speechbrain.nnet.activations.Softmax
        apply_log: True

modules: {model: !ref <model>, mean_var_norm: !ref <mean_var_norm>}

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

compute_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: 42

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
