# ################################
# Model: Speaker Diarization Baseline
# Authors: Nauman Dawalatabad 2020
# ################################

seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder_vox: /network/datasets/restricted/voxceleb_users/voxceleb/voxceleb1/
data_folder_ami: /network/datasets/ami/amicorpus/
output_folder: results/
save_folder: !ref <output_folder>/save/
device: 'cuda:0'

# Pretrain from web (as an alternative specify a file)
xvector_file: https://www.dropbox.com/s/skfz2sme5nw7jji/xvector_model.ckpt?dl=1

# csv files
csv_train: !ref <save_folder>/train.csv
csv_diary: !ref <save_folder>/eval.subsegments.csv
batch_size: 128

# Spectral feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False
xvect_dim: 512

# Diarization parameters
split_type: 'sample'
mic_type: 'hm'
vad_type: 'oracle'
max_subseg_dur: 3.0
overlap: 1.5

compute_plda: !new:speechbrain.processing.PLDA_LDA.PLDA
    rank_f: 100
    nb_iter: 10
    scaling_factor: 1

# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

mean_var_norm_xvect: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

xvector_model: !new:speechbrain.lobes.models.Xvector.Xvector
    device: !ref <device>

train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    csv_read: [wav, spk_id]
    sentence_sorting: ascending
    replacements:
        $data_folder: !ref  <data_folder_vox>
    output_folder: !ref <output_folder>/save/

diary_loader:
    csv_file: !ref <csv_diary>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: original
    replacements:
        $data_folder: !ref <data_folder_ami>
    output_folder: !ref <output_folder>/save/
