# ################################
# Model: Speaker Diarization Baseline on deep embedding + spectral clustering
# Authors: Nauman Dawalatabad 2020
# ################################

seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Folders
data_folder: /network/datasets/ami/amicorpus
manual_annot_folder: /home/mila/d/dawalatn/nauman/ami_public_manual
output_folder: results/ami/speaker_diarization_xvector/
save_folder: !ref <output_folder>/save
device: 'cuda:0'

# Embedding model
embedding_file: https://www.dropbox.com/sh/egbd9jsywbsjm45/AADp96m552bo5lsahR5hmmzMa/save/CKPT%2B2020-09-07%2B08-34-27%2B00/embedding_model.ckpt?dl=1 # yamllint disable-line rule:line-length

model_dir: !ref <save_folder>/emb_model

# Some more exp folders (for cleaner structure)
embedding_dir: !ref <save_folder>/emb
csv_dir: !ref <save_folder>/csv
ref_rttm_dir: !ref <save_folder>/ref_rttms
sys_rttm_dir: !ref <save_folder>/sys_rttms

# AMI: csv files
csv_diary_train: !ref <save_folder>/csv/ami_train.subsegments.csv
csv_diary_dev: !ref <save_folder>/csv/ami_dev.subsegments.csv
csv_diary_eval: !ref <save_folder>/csv/ami_eval.subsegments.csv

# Spectral feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Xvector model
emb_dim: 512
batch_size: 128

# AMI data_prep parameters
split_type: 'full_corpus_asr'
skip_TNO: True
mic_type: 'Lapel'
vad_type: 'oracle'
max_subseg_dur: 3.0
overlap: 1.5

# Cluster parameters
max_num_spkrs: 10
min_num_spkrs: 2
oracle_n_spkrs: True
n_neighbors: 10
include_self: True
p_val: 0.01

# DER evaluation parameters
ignore_overlap: True
forgiveness_collar: 0.25


# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

mean_var_norm_emb: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.Xvector.Xvector
    device: !ref <device>

diary_loader_train: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_diary_train>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: original
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

diary_loader_dev: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_diary_dev>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: original
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

diary_loader_eval: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_diary_eval>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: original
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/
