# ################################00000
# Model: Speaker Diarization Baseline
# Authors: Nauman Dawalatabad 2020
# ################################

seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder: /network/datasets/ami/amicorpus
manual_annot_folder: /network/tmp1/dawalatn/AMI_MANUAL
output_folder: results
save_folder: !ref <output_folder>/save
device: 'cuda:0'

# Vox1+Vox2
xvector_f: >
    https://www.dropbox.com/sh/egbd9jsywbsjm45/AADp96m552bo5lsahR5hmmzMa/
    save/CKPT%2B2020-09-07%2B08-34-27%2B00/embedding_model.ckpt?dl=1
model_dir: !ref <save_folder>/model_tdnn_vox1and2

# Exp directories
xvect_dir: !ref <save_folder>/xvectors
csv_dir: !ref <save_folder>/csv
ref_rttm_dir: !ref <save_folder>/ref_rttms
sys_rttm_dir: !ref <save_folder>/sys_rttms

# Vox: csv files
csv_train_vox: !ref <save_folder>/train.csv
csv_enrol_vox: !ref <save_folder>/enrol.csv
csv_test_vox: !ref <save_folder>/test.csv

# AMI: csv files
csv_diary_train: !ref <save_folder>/csv/ami_train.subsegments.csv
csv_diary_dev: !ref <save_folder>/csv/ami_dev.subsegments.csv
csv_diary_eval: !ref <save_folder>/csv/ami_eval.subsegments.csv


# Spectral feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Xvector model
xvect_dim: 512
batch_size: 128

# AMI data_prep parameters
split_type: 'full_corpus_asr'
mic_type: 'Lapel'
vad_type: 'oracle'
max_subseg_dur: 3.0
overlap: 1.5

# DER evaluation parameters
ignore_overlap: True
forgiveness_collar: 0.25


# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

mean_var_norm_xvect: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

xvector_model: !new:speechbrain.lobes.models.Xvector.Xvector
    device: !ref <device>

diary_loader_train: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_diary_train>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: original
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

diary_loader_dev: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_diary_dev>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: original
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/

diary_loader_eval: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_diary_eval>
    batch_size: !ref <batch_size>
    csv_read: [wav]
    sentence_sorting: original
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/
