# ################################
# Model: Speaker Verification Baseline
# Authors: Mirco Ravanelli 2020
# ################################

seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
data_folder: /home/mirco/datasets/VoxCeleb1
output_folder: results/speaker_verification
save_folder: !ref <output_folder>/save/
device: 'cuda:0'

# Pretrain from web (as an alternative specify a file)
pretrain_file: https://www.dropbox.com/s/skfz2sme5nw7jji/xvector_model.ckpt?dl=1
normalizer_file: https://www.dropbox.com/s/4qh5lt49lau0nx2/normalizer.ckpt?dl=1
classifier_file: https://www.dropbox.com/s/ure85nam6ok0au7/classifier.ckpt?dl=1

# csv files
csv_test: !ref <save_folder>/test.csv
batch_size: 4

# Feature parameters
n_mels: 24
left_frames: 0
right_frames: 0
deltas: False

# Functions
compute_features: !new:speechbrain.lobes.features.fbank.Fbank
    n_mels: !ref <n_mels>
    left_frames: !ref <left_frames>
    right_frames: !ref <right_frames>
    deltas: !ref <deltas>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

mean_var_norm_xvect: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

xvector_model: !new:speechbrain.lobes.models.Xvector.Xvectors
    device: !ref <device>
    save_web_model: !ref <output_folder>/save/xvector.ckpt

classifier: !new:speechbrain.lobes.models.Xvector.Classifier
    activation: !name:torch.nn.LeakyReLU
    device: cuda:0
    lin_blocks: 1
    lin_neurons: 512
    out_neurons: 1211

test_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>
    csv_read: [wav1, wav2, lab_verification]
    sentence_sorting: random
    replacements:
        $data_folder: !ref <data_folder>
    output_folder: !ref <output_folder>/save/
