# ############################################################################
# Model: LM for Timers and Such
# Tokens: Pre-trained LibriSpeech tokens
# losses: NLL
# Training: Timers and Such
# Authors:  Loren Lugosch 2020
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1992
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/RNNLM_1024/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: /localscratch/timers-and-such
train_splits: ["train-synth", "train-real"]
dev_split: dev-real
csv_train: !ref <data_folder>/train-type=decoupled.csv
csv_valid: !ref <data_folder>/<dev_split>-type=decoupled.csv
csv_test_synth: !ref <data_folder>/test-synth-type=decoupled.csv
csv_test_real: !ref <data_folder>/test-real-type=decoupled.csv
asr_hparam_file:
    ../../../recipes/LibriSpeech/ASR/seq2seq/hparams/pretrained.yaml

# Training parameters
number_of_epochs: 10
batch_size: 128
lr: 0.0003
device: 'cuda:0'
ddp_procs: 0  # Set to number of GPUs for multi-gpu training
token_type: unigram # ["unigram", "bpe", "char"]


# Model params
sample_rate: 16000
emb_size: 128
net_dim: 1024
num_asr_tokens: 1000
#output_neurons: 51 # index(eos/bos) = 0

# Decoding parameters
bos_index: 0
eos_index: 0

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Dataloaders
train_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: random
    output_folder: !ref <output_folder>
    csv_read: [transcript]

valid_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [transcript]

test_real_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test_real>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [transcript]

test_synth_loader: !new:speechbrain.data_io.data_io.DataLoaderFactory
    csv_file: !ref <csv_test_synth>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [transcript]

# Models
asr_model: !new:recipes.LibriSpeech.ASR.seq2seq.pretrained.ASR
    hparams_file: !ref <asr_hparam_file>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

modules:
    net: !ref <net>
    log_softmax: !ref <log_softmax>

net: !new:speechbrain.lobes.models.RNNLM.RNNLM
    output_neurons: !ref <num_asr_tokens>
    embedding_dim: !ref <emb_size>
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.
    rnn_layers: 2
    rnn_neurons: !ref <net_dim>
    dnn_blocks: 1
    dnn_neurons: !ref <net_dim>

model: !ref <net>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

seq_cost: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.1

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True
