
# ############################################################################
# Tokenizer: subword BPE tokenizer with BPE 1K
# Training: Fisher-Callhome 160h
# Authors:  YAO-FEI, CHENG 2021
# ############################################################################


# Set up folders for reading from and writing to
original_data_folder: !PLACEHOLDER # i.e., path to your data
data_folder: ../data
output_folder: ./save
device: 'cuda:0' # for resample audio

# Tokenizer parameters
token_type: bpe  # ["unigram", "bpe", "char"]
token_output: 1000  # index(blank/eos/bos/unk) = 0
annotation_read: ["translation_0", "transcription"] # field to read

# Tokenizer object
tokenizer: !name:speechbrain.tokenizers.SentencePiece.SentencePiece
   model_dir: !ref <output_folder>
   vocab_size: !ref <token_output>
   annotation_train: ../data/train/data.json
   annotation_read: !ref <annotation_read>
   model_type: !ref <token_type> # ["unigram", "bpe", "char"]
   annotation_list_to_check: [../data/train/data.json]
   annotation_format: json
   bos_id: 1
   eos_id: 2
   unk_id: 0