# Seed needs to be set at top of yaml, before objects with parameters are made
# NOTE: Seed does not guarantee replicability with CTC
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data files
data_folder: !PLACEHOLDER

# Neural Parameters
N_epochs: 10
batch_size: 1
lr: 0.002
# token infomation
eos_bos_index: 1
blank_index: 0

# Model parameters
activation: !name:torch.nn.LeakyReLU []
dropout: 0.15
cnn_blocks: 1
cnn_channels: (16,)
cnn_kernelsize: (3, 3)
rnn_layers: 1
rnn_neurons: 128
rnn_bidirectional: True
dnn_blocks: 1
dnn_neurons: 128

label_encoder: !new:speechbrain.data_io.encoder.CTCTextEncoder

common_dynamic_items:
    phn_list:
        func: !name:speechbrain.utils.data_utils.split_by_whitespace
        argkeys: [phn]
    phn_encoded:
        func: !ref <label_encoder.encode_sequence>
        argkeys: [phn_list]
    phn_encoded_eos:
        func: !new:speechbrain.utils.data_utils.FuncPipeline
            - !ref <label_encoder.append_eos_index>
            - !name:speechbrain.data_io.data_io.to_longTensor
        argkeys: [phn_encoded]
    phn_encoded_bos:
        func: !new:speechbrain.utils.data_utils.FuncPipeline
            - !ref <label_encoder.prepend_bos_index>
            - !name:speechbrain.data_io.data_io.to_longTensor
        argkeys: [phn_encoded]
    sig:
        func: !name:speechbrain.data_io.data_io.read_audio
        argkeys: [wav]
common_output_keys: ["id", "sig", "phn_encoded_eos", "phn_encoded_bos"]

train_data: !apply:speechbrain.data_io.dataset.DynamicItemDataset.from_json
    json_path: !ref <data_folder>/train.json
    replacements:
        data_root: !ref <data_folder>
    dynamic_items: !ref <common_dynamic_items>
    output_keys: !ref <common_output_keys>

valid_data: !apply:speechbrain.data_io.dataset.DynamicItemDataset.from_json
    json_path: !ref <data_folder>/dev.json
    replacements:
        data_root: !ref <data_folder>
    dynamic_items: !ref <common_dynamic_items>
    output_keys: !ref <common_output_keys>

compute_features: !new:speechbrain.lobes.features.MFCC

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, 660]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: 45  # 44 phonemes + 1 eos_bos
    bias: False

emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: 45  # 45 phonemes + 1 bos
    embedding_dim: 128

dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: 128
    input_size: 128
    rnn_type: gru
    attn_type: content
    hidden_size: !ref <rnn_neurons>
    attn_dim: !ref <rnn_neurons>
    num_layers: 1

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

modules:
    enc: !ref <enc>
    emb: !ref <emb>
    dec: !ref <dec>
    lin: !ref <lin>
    mean_var_norm: !ref <mean_var_norm>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

searcher: !new:speechbrain.decoders.seq2seq.S2SRNNGreedySearcher
    embedding: !ref <emb>
    decoder: !ref <dec>
    linear: !ref <lin>
    bos_index: !ref <eos_bos_index>
    eos_index: !ref <eos_bos_index>
    blank_index: !ref <blank_index>
    min_decode_ratio: 0
    max_decode_ratio: 0.1

compute_cost: !name:speechbrain.nnet.losses.nll_loss

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
