# Seed needs to be set at top of yaml, before objects with parameters are made
# NOTE: Seed does not guarantee replicability with CTC
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]


# Neural Parameters
N_epochs: 15
batch_size: 1
lr: 0.002
blank_index: 44

# Model parameters
activation: !name:torch.nn.LeakyReLU []
dropout: 0.15
cnn_blocks: 1
cnn_channels: (16,)
cnn_kernelsize: (3, 3)
rnn_layers: 1
rnn_neurons: 128
rnn_bidirectional: True
dnn_blocks: 1
dnn_neurons: 128

# Data:
data_folder: !PLACEHOLDER
# TODO: Replace with final implementations
label_encoder: !new:placeholders.ExampleCategoricalEncoder
    label2ind: !name:placeholders.ASR_example_label2ind
    ind2label: !name:placeholders.ASR_example_ind2label

text_transform: !new:speechbrain.utils.data_utils.FuncPipeline
    name: text_transform
    target: phns
    funcs:
        - !name:speechbrain.utils.data_utils.split_by_whitespace
        - !ref <label_encoder.encode_list>
        - !name:speechbrain.data_io.data_io.to_longTensor

train_data: !apply:speechbrain.data_io.datasets.SegmentedDataset.from_extended_yaml
    filepath: !ref <data_folder>/train.yaml
    overrides:
        data_root: !ref <data_folder>
    data_fields: [wav, phn]
    data_transforms:
        wav: !name:placeholders.torchaudio_load
        phn: !ref <text_transform>

valid_data: !apply:speechbrain.data_io.datasets.SegmentedDataset.from_extended_yaml
    filepath: !ref <data_folder>/dev.yaml
    overrides:
        data_root: !ref <data_folder>
    data_fields: [wav, phn]
    data_transforms:
        wav: !name:placeholders.torchaudio_load
        phn: !ref <text_transform>

train_loader: !new:speechbrain.data_io.dataloader.SaveableDataLoader
    dataset: !ref <train_data>
    batch_size: !ref <batch_size>
    collate_fn: !name:speechbrain.data_io.dataloader.collate_pad

valid_loader: !new:speechbrain.data_io.dataloader.SaveableDataLoader
    dataset: !ref <valid_data>
    batch_size: !ref <batch_size>
    collate_fn: !name:speechbrain.data_io.dataloader.collate_pad

compute_features: !new:speechbrain.lobes.features.MFCC

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

model: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, 660]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: 45  # 44 phonemes + 1 blank
    bias: False

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

compute_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

modules:
    model: !ref <model>
    lin: !ref <lin>
    mean_var_norm: !ref <mean_var_norm>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
