# ################################
# Model: VGG2 + LiGRU with time pooling for efficiency
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1319
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/joint_asr_bpe_lm/<seed>
stats_file: !ref <output_folder>/stats.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

lm_ckpt_file: https://www.dropbox.com/s/6uy5m6jaf0t769i/model.ckpt?dl=1
tok_mdl_file: https://www.dropbox.com/s/o7gnouwdoqchotj/1000_unigram.model?dl=1
tok_voc_file: https://www.dropbox.com/s/7l8z622cpd3t8st/1000_unigram.vocab?dl=1

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/TIMIT
data_folder_rirs: !ref <data_folder>
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/valid.csv
csv_test: !ref <data_folder>/test.csv

# Training parameters
number_of_epochs: 20
ctc_epochs: 0
batch_size: 8
lr: 0.0001
token_type: unigram
target_type: wrd
device: 'cuda:0'
multigpu_count: 0  # Set to number of GPUs if multi-gpu
checkpoint_avg: 5  # average this many checkpoints for eval

# Loss weights
enhance_type: masking  # null, mapping, masking
enhance_weight: 0.0
mimic_weight: 0.0
ctc_weight: 1.0
ctc_type: joint  # null, clean, joint
seq_weight: 1.0
seq_type: joint  # null, clean, joint
alignment_weight: 0.0
label_smoothing: 0.1

# Set this to the path of a pretrained model to load before training
pretrained_path:
    enhance_model: biphn_mimic_transformer/enhance_model.ckpt
    # enhance_model: transformer_crdnn_base10/enhance_model.ckpt
    # enhance_model: results/masking/enhance_model.ckpt

frozen_models: [enhance_model, src_embedding]
unfreeze_epoch: 4
unfrozen_models: [src_embedding]

# Feature parameters
sample_rate: 16000
n_fft: 512
win_length: 32
hop_length: 16
n_mels: 40
emb_size: 128

# Masker parameters
emb_channels: 1024
emb_kernel_size: 3
emb_padding: same
enhancer_size: 512
enhancer_layers: 8
enhancer_heads: 8
enhancer_causal: False
enhancer_activation: !name:torch.nn.LeakyReLU
enhancer_output_activation: !name:torch.nn.ReLU
enhancer_drop_rate: 0.1

# Src embedding parameters
src_activation: !name:torch.nn.LeakyReLU
src_dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
cnn_kernelsize: (3, 3)
rnn_layers: 4
rnn_neurons: 1024
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512

# Decoder params
dec_neurons: 1024
dec_rnn_type: gru
dec_attn_type: location
dec_attn_dim: 1024
dec_channels: 10
dec_kernel: 100
dec_layers: 1
dec_dropout: 0.15

# Decoding params
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 16
eos_threshold: 1.5
using_max_attn_shift: True
max_attn_shift: 240
lm_weight: 0.2
coverage_penalty: 1.5
temperature: 1.25
temperature_lm: 1.25

# Language model params
lm_emb_size: 128
lm_activation: !name:torch.nn.LeakyReLU
lm_dropout: 0.0
lm_rnn_layers: 2
lm_rnn_neurons: 2048
lm_dnn_blocks: 1
lm_dnn_neurons: 512

# Outputs
output_neurons: 1000
blank_index: 0
bos_index: 0
eos_index: 0

epoch_counter: !new:speechbrain.EpochCounter
    limit: !ref <number_of_epochs>

train_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [noisy_wav, clean_wav, !ref <target_type>]

valid_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [noisy_wav, clean_wav, !ref <target_type>]

test_loader: !new:speechbrain.data_io.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [noisy_wav, clean_wav, !ref <target_type>]

compute_stft: !new:speechbrain.processing.STFT
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>

compute_istft: !new:speechbrain.processing.ISTFT
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    win_length: !ref <win_length>
    hop_length: !ref <hop_length>

spectral_magnitude: !name:speechbrain.processing.spectral_magnitude
    power: 0.5

resynth: !name:speechbrain.processing.resynthesize
    stft: !ref <compute_stft>
    istft: !ref <compute_istft>

env_corr: !new:speechbrain.lobes.EnvCorrupt
    openrir_folder: !ref <data_folder_rirs>
    babble_prob: 0.0
    reverb_prob: 0.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15

augment: !new:speechbrain.lobes.TimeDomainSpecAugment
fbank: !new:speechbrain.lobes.Fbank
    n_mels: !ref <n_mels>
    sample_rate: !ref <sample_rate>
normalizer: !new:speechbrain.processing.InputNormalization

embedding_module: !new:embedding.CNNEmbedding
    input_shape: [null, null, !ref <n_fft> // 2 + 1]
    base_channels: !ref <emb_channels>

enhance_model: !new:speechbrain.lobes.CNNTransformerSE
    output_size: !ref <n_fft> // 2 + 1
    input_size: !ref <n_fft> // 2
    d_model: !ref <n_fft> // 2
    output_activation: !ref <enhancer_output_activation>
    activation: !ref <enhancer_activation>
    dropout: !ref <enhancer_drop_rate>
    num_layers: !ref <enhancer_layers>
    d_ffn: !ref <enhancer_size>
    nhead: !ref <enhancer_heads>
    causal: !ref <enhancer_causal>
    custom_emb_module: !ref <embedding_module>

src_embedding: !new:speechbrain.lobes.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <src_activation>
    dropout: !ref <src_dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    time_pooling_size: 4
    rnn_class: !name:speechbrain.nnet.LSTM
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

tgt_embedding: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

recognizer: !new:speechbrain.nnet.AttentionalRNNDecoder
    rnn_type: !ref <dec_rnn_type>
    attn_type: !ref <dec_attn_type>
    enc_dim: !ref <dnn_neurons>
    input_size: !ref <emb_size>
    hidden_size: !ref <dec_neurons>
    attn_dim: !ref <dec_attn_dim>
    channels: !ref <dec_channels>
    kernel_size: !ref <dec_kernel>
    num_layers: !ref <dec_layers>
    dropout: !ref <dec_dropout>

ctc_output: !new:speechbrain.nnet.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>

seq_output: !new:speechbrain.nnet.Linear
    input_size: !ref <dec_neurons>
    n_neurons: !ref <output_neurons>

model: !new:torch.nn.ModuleList [[
    !ref <src_embedding>,
    !ref <tgt_embedding>,
    !ref <recognizer>,
    !ref <ctc_output>,
    !ref <seq_output>,
]]

log_softmax: !new:speechbrain.nnet.Softmax
    apply_log: True

lm_model: !new:speechbrain.lobes.RNNLM
    output_neurons: !ref <output_neurons>
    embedding_dim: !ref <emb_size>
    activation: !ref <lm_activation>
    dropout: !ref <lm_dropout>
    rnn_layers: !ref <lm_rnn_layers>
    rnn_neurons: !ref <lm_rnn_neurons>
    dnn_blocks: !ref <lm_dnn_blocks>
    dnn_neurons: !ref <lm_dnn_neurons>
    return_hidden: True

beam_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNBeamSearchLM
    embedding: !ref <tgt_embedding>
    decoder: !ref <recognizer>
    linear: !ref <seq_output>
    language_model: !ref <lm_model>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <beam_size>
    eos_threshold: !ref <eos_threshold>
    using_max_attn_shift: !ref <using_max_attn_shift>
    max_attn_shift: !ref <max_attn_shift>
    coverage_penalty: !ref <coverage_penalty>
    lm_weight: !ref <lm_weight>
    temperature: !ref <temperature>
    temperature_lm: !ref <temperature_lm>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.StepScheduler
    initial_value: !ref <lr>
    decay_factor: 0.5
    decay_drop: 3

modules:
    enhance_model: !ref <enhance_model>
    src_embedding: !ref <src_embedding>
    tgt_embedding: !ref <tgt_embedding>
    recognizer: !ref <recognizer>
    ctc_output: !ref <ctc_output>
    seq_output: !ref <seq_output>
    lm_model: !ref <lm_model>

checkpointer: !new:speechbrain.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        enhance_model: !ref <enhance_model>
        src_embedding: !ref <src_embedding>
        tgt_embedding: !ref <tgt_embedding>
        recognizer: !ref <recognizer>
        ctc_output: !ref <ctc_output>
        seq_output: !ref <seq_output>
        counter: !ref <epoch_counter>
        normalizer: !ref <normalizer>

pretrain_checkpointer: !new:speechbrain.Checkpointer
    checkpoints_dir: pretrain
    recoverables:
        model: !ref <model>
        normalizer: !ref <normalizer>

enhance_loss: !name:speechbrain.nnet.mse_loss
mimic_loss: !name:speechbrain.nnet.mse_loss
ctc_loss: !name:speechbrain.nnet.ctc_loss
    blank_index: !ref <blank_index>
seq_loss: !name:speechbrain.nnet.nll_loss
    label_smoothing: !ref <label_smoothing>

enhance_stats: !name:speechbrain.MetricStats
    metric: !name:speechbrain.nnet.mse_loss
        reduction: batch
stoi_stats: !name:speechbrain.MetricStats
    metric: !name:speechbrain.nnet.loss.stoi_loss.stoi_loss
        reduction: batch
mimic_stats: !name:speechbrain.MetricStats
    metric: !name:speechbrain.nnet.mse_loss
        reduction: batch
ctc_stats: !name:speechbrain.MetricStats
    metric: !name:speechbrain.nnet.ctc_loss
        blank_index: !ref <blank_index>
        reduction: batch
seq_stats: !name:speechbrain.MetricStats
    metric: !name:speechbrain.nnet.nll_loss
        label_smoothing: !ref <label_smoothing>
        reduction: batch
err_rate_stats: !name:speechbrain.ErrorRateStats

train_logger: !new:speechbrain.FileTrainLogger
    save_file: !ref <train_log>
