# ################################
# Model: VGG2 + LSTM + time pooling
# Augmentation: TimeDomainSpecAugment + noise
# Additions: BPE
# Authors: Mirco Ravanelli, Peter Plantinga, Ju-Chieh Chou, Abdel HEBA 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/CRDNN_BPE_100h_LM/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
lm_ckpt_file: https://www.dropbox.com/s/6uy5m6jaf0t769i/model.ckpt?dl=1

# Tokenizer model
tok_mdl_file: https://www.dropbox.com/s/o7gnouwdoqchotj/1000_unigram.model?dl=1
tok_voc_file: https://www.dropbox.com/s/7l8z622cpd3t8st/1000_unigram.vocab?dl=1

# Data files
data_folder: /localscratch/LibriSpeech
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded
data_folder_rirs: !ref <data_folder>
train_splits: ["train-clean-100"]
dev_split: dev-clean
test_split: test-clean

csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/<dev_split>.csv
csv_test: !ref <data_folder>/<test_split>.csv

# Training parameters
number_of_epochs: 30
number_of_ctc_epochs: 10
batch_size: 8
lr: 1.0
ctc_weight: 0.5
device: 'cuda'
# allow token error rate computation
ter_eval: True

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
inter_layer_pooling_size: (2, 2)
cnn_kernelsize: (3, 3)
time_pooling_size: 4
rnn_class: !name:speechbrain.nnet.LSTM
rnn_layers: 4
rnn_neurons: 1024
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512
emb_size: 128
dec_neurons: 1024

# Outputs
output_neurons: 1000  # index(blank/eos/bos) = 0
blank_index: 0
# Decoding parameters
# Be sure that the bos and eos index match with the BPEs ones
bos_index: 0
eos_index: 0
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 64
eos_threshold: 1.5
using_max_attn_shift: True
max_attn_shift: 170
lm_weight: 0.45

# LM Model parameters
lm_emb_size: 128
lm_activation: !name:torch.nn.LeakyReLU
lm_dropout: 0.0
lm_rnn_layers: 2
lm_rnn_neurons: 2048
lm_dnn_blocks: 1
lm_dnn_neurons: 512

train_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_train>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, wrd]

valid_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_valid>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, wrd]

test_loader: !new:speechbrain.DataLoaderFactory
    csv_file: !ref <csv_test>
    batch_size: !ref <batch_size>
    sentence_sorting: ascending
    output_folder: !ref <output_folder>
    csv_read: [wav, wrd]

modules:
    save_folder: !ref <save_folder>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    ctc_weight: !ref <ctc_weight>
    wer_file: !ref <wer_file>
    ter_eval: !ref <ter_eval>
    output_folder: !ref <output_folder>
    lm_ckpt_file: !ref <lm_ckpt_file>
    tok_mdl_file: !ref <tok_mdl_file>
    tok_voc_file: !ref <tok_voc_file>
    number_of_ctc_epochs: !ref <number_of_ctc_epochs>
    lm_model: !new:speechbrain.lobes.RNNLM
        output_neurons: !ref <output_neurons>
        embedding_dim: !ref <emb_size>
        activation: !ref <lm_activation>
        dropout: !ref <lm_dropout>
        rnn_layers: !ref <lm_rnn_layers>
        rnn_neurons: !ref <lm_rnn_neurons>
        dnn_blocks: !ref <lm_dnn_blocks>
        dnn_neurons: !ref <lm_dnn_neurons>
        return_hidden: True  # For inference
    enc: !new:speechbrain.lobes.CRDNN
        input_shape: [null, null, !ref <n_mels>]
        activation: !ref <activation>
        dropout: !ref <dropout>
        cnn_blocks: !ref <cnn_blocks>
        cnn_channels: !ref <cnn_channels>
        cnn_kernelsize: !ref <cnn_kernelsize>
        inter_layer_pooling_size: !ref <inter_layer_pooling_size>
        time_pooling: True
        using_2d_pooling: False
        time_pooling_size: !ref <time_pooling_size>
        rnn_class: !ref <rnn_class>
        rnn_layers: !ref <rnn_layers>
        rnn_neurons: !ref <rnn_neurons>
        rnn_bidirectional: !ref <rnn_bidirectional>
        rnn_re_init: True
        dnn_blocks: !ref <dnn_blocks>
        dnn_neurons: !ref <dnn_neurons>
    emb: !new:speechbrain.nnet.Embedding
        num_embeddings: !ref <output_neurons>
        embedding_dim: !ref <emb_size>
    dec: !new:speechbrain.nnet.AttentionalRNNDecoder
        enc_dim: !ref <dnn_neurons>
        input_size: !ref <emb_size>
        rnn_type: gru
        attn_type: location
        hidden_size: !ref <dec_neurons>
        attn_dim: 1024
        num_layers: 1
        scaling: 1.0
        channels: 10
        kernel_size: 100
        re_init: True
        dropout: !ref <dropout>
    ctc_lin: !new:speechbrain.nnet.Linear
        input_size: !ref <dnn_neurons>
        n_neurons: !ref <output_neurons>
    seq_lin: !new:speechbrain.nnet.Linear
        input_size: !ref <dec_neurons>
        n_neurons: !ref <output_neurons>
    log_softmax: !new:speechbrain.nnet.Softmax
        apply_log: True

    # Use nested list, since ModuleList takes a list as a parameter
    model: !new:torch.nn.ModuleList [[
        !ref <modules.enc>,
        !ref <modules.emb>,
        !ref <modules.dec>,
        !ref <modules.ctc_lin>,
        !ref <modules.seq_lin>
    ]]
    greedy_searcher: !new:speechbrain.decoders.S2SRNNGreedySearcher
        modules:
            - !ref <modules.emb>
            - !ref <modules.dec>
            - !ref <modules.seq_lin>
        bos_index: !ref <bos_index>
        eos_index: !ref <eos_index>
        min_decode_ratio: !ref <min_decode_ratio>
        max_decode_ratio: !ref <max_decode_ratio>
    beam_searcher: !new:speechbrain.decoders.S2SRNNBeamSearchLM
        modules:
            - !ref <modules.emb>
            - !ref <modules.dec>
            - !ref <modules.seq_lin>
            - !ref <modules.lm_model>
        bos_index: !ref <bos_index>
        eos_index: !ref <eos_index>
        min_decode_ratio: !ref <min_decode_ratio>
        max_decode_ratio: !ref <max_decode_ratio>
        beam_size: !ref <beam_size>
        eos_threshold: !ref <eos_threshold>
        using_max_attn_shift: !ref <using_max_attn_shift>
        lm_weight: !ref <lm_weight>
    optimizer: !new:torch.optim.Adadelta
        params: !!python/object/apply:speechbrain.collect_params
            - !ref <modules.model>
        lr: !ref <lr>
        rho: 0.95
        eps: 1.e-8
    lr_annealing: !new:speechbrain.nnet.NewBobScheduler
        initial_value: !ref <lr>
        improvement_threshold: 0.0025
        annealing_factor: 0.8
        patient: 0
    normalize: !new:speechbrain.processing.InputNormalization
        norm_type: global
    epoch_counter: !new:speechbrain.EpochCounter
        limit: !ref <number_of_epochs>
    env_corrupt: !new:speechbrain.lobes.EnvCorrupt
        openrir_folder: !ref <data_folder_rirs>
        babble_prob: 0.0
        reverb_prob: 0.0
        noise_prob: 1.0
        babble_speaker_count: 7
        babble_snr_low: 10
        babble_snr_high: 10
        noise_snr_low: 0
        noise_snr_high: 15
        rir_scale_factor: 1.0
    augmentation: !new:speechbrain.lobes.TimeDomainSpecAugment
        sample_rate: !ref <sample_rate>
        speeds: [95, 100, 105]
    compute_features: !new:speechbrain.lobes.Fbank
        sample_rate: !ref <sample_rate>
        n_fft: !ref <n_fft>
        n_mels: !ref <n_mels>
    ctc_cost: !name:speechbrain.nnet.ctc_loss
        blank_index: !ref <blank_index>
    seq_cost: !name:speechbrain.nnet.nll_loss
        label_smoothing: 0.1
    train_logger: !new:speechbrain.FileTrainLogger
        save_file: !ref <train_log>
    error_rate_computer: !name:speechbrain.ErrorRateStats
    cer_computer: !name:speechbrain.ErrorRateStats
        split_tokens: True
    checkpointer: !new:speechbrain.Checkpointer
        checkpoints_dir: !ref <save_folder>
        recoverables:
            model: !ref <modules.model>
            optimizer: !ref <modules.optimizer>
            scheduler: !ref <modules.lr_annealing>
            normalizer: !ref <modules.normalize>
            counter: !ref <modules.epoch_counter>
